<a href="https://colab.research.google.com/github/Jorge-742/TalenTech_Exercise_Practice/blob/main/Laboratorio__7_python_pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios Python Laboratorio 7


In [ ]:
import pandas as pd
import numpy as np




---



**Ejercicio de práctica 1.**

Crear un DataFrame con los nombres, profesión y países de 8 personas, y luego imprimir el DataFrame.


In [ ]:
DataFrame = pd.DataFrame({
    'Nombres':['Juan', 'Carlos', 'Miguel', 'Andra', 'Maria', 'Julio', 'Jose', 'Jean Carlos'],
    'Profesion': ['Ingeniero', 'Enfermero', 'Arquitecto', 'Modelo', 'Actriz', 'Ingeniero', 'Analista de datos', 'Cocinero'],
    'Pais' : ['Perú', 'Colombia', 'España','Costa Rica', 'Argentina', 'Brasil', 'Brasil', 'Bolivia']})
print(DataFrame)

       Nombres          Profesion        Pais
0         Juan          Ingeniero        Perú
1       Carlos          Enfermero    Colombia
2       Miguel         Arquitecto      España
3        Andra             Modelo  Costa Rica
4        Maria             Actriz   Argentina
5        Julio          Ingeniero      Brasil
6         Jose  Analista de datos      Brasil
7  Jean Carlos           Cocinero     Bolivia




---



Cargar un archivo CSV (puedes usar un archivo de ejemplo en tu entorno) y mostrar las primeras 5 filas.


In [ ]:
sales_data = pd.read_csv('/content/drive/MyDrive/Sales.csv')
df = sales_data.head(5)
print(df)

   SalesId  StoreId  ProductId        Date  UnitPrice  Quantity
0    82319    22726        590  2019-12-02     0.0525        93
1    15022    21754        390  2017-11-19     5.1100        28
2    11624    71053        883  2020-07-13     7.3675        33
3    63101    22914        658  2019-05-12     2.0825        76
4    29702    22623        632  2020-07-20     0.6475         8




---



Generar un DataFrame con 100 filas y 8 columnas de valores aleatorios, y luego mostrar un resumen estadístico de los datos.

In [ ]:
DataFrame = pd.DataFrame(np.random.rand(100, 8))
Vistas = DataFrame.describe()
print(Vistas)

                0           1           2           3           4           5  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.500592    0.526636    0.527470    0.535112    0.474175    0.518227   
std      0.308261    0.268698    0.282276    0.296147    0.286656    0.300412   
min      0.010073    0.014175    0.000210    0.003219    0.010659    0.006228   
25%      0.208084    0.299384    0.306646    0.298597    0.202924    0.260664   
50%      0.509262    0.516881    0.543184    0.533812    0.482272    0.515273   
75%      0.758703    0.750542    0.762887    0.770965    0.693833    0.773500   
max      0.996881    0.998501    0.990884    0.998347    0.984995    0.986213   

                6           7  
count  100.000000  100.000000  
mean     0.483047    0.536938  
std      0.257704    0.269565  
min      0.015354    0.019726  
25%      0.274681    0.306422  
50%      0.474533    0.544652  
75%      0.679280    0.754175  
max      0.985



---



**Ejercicio de práctica 2.**


Crear un array de números del 1 al 10 y mostrar la suma, la media, y el valor máximo.


In [ ]:
crea_array = np.array(range(1,11))
suma_array = crea_array.sum()
media_array = crea_array.mean()
max_array = crea_array.max()

print(suma_array) # Suma de array
print(media_array) # Promedio
print(max_array) # Valor maximo


55
5.5
10




---



Crear un array de 3x4 lleno de ceros y luego cambiar su forma a 2x6.


In [ ]:
arr_1 = np.zeros((3,4)) # crea un array de 3x4 con datos en cero.

arr_2 = arr_1.reshape((2,6)) # modifica el array de 3x4 a 2x6.
print(arr_2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]




---



Generar una matriz aleatoria de 3x3 y calcular su transpuesta.


In [11]:
arr_3 = np.random.randint(1, 1000, (3,3)) #genera la mariz con números enteros aleatorios que se encuentren entre 1 y 1000.
print(arr_3)

[[792 626 127]
 [433 785  13]
 [516 563 176]]


In [14]:
calculo_transpuesta = arr_3.transpose() # Con el método .transpose() se calcula la transposición del array.
print(calculo_transpuesta)

[[792 433 516]
 [626 785 563]
 [127  13 176]]




---



Concatenar dos arrays de NumPy, cada uno con 5 valores, y luego imprimir el array concatenado

In [19]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c = np.concatenate((a, b)) # concatena el array a con el b
print(c)


[ 1  2  3  4  5  6  7  8  9 10]




---

